### ISSUE TITLE
Why minreq appends extra \r\n to the response body ?

### ISSUE THREAD

**Issue by shanavas786** [neonmoe/minreq#12]
minreq appends `\r\n` to request body [here](https://github.com/neonmoe/minreq/blob/master/src/http.rs#L243). I couldn't find a good reason for that.

**Comment by shanavas786** [comment]
[There](https://github.com/neonmoe/minreq/blob/master/tests/setup.rs#L135-L143) is  wrapper in tests to get rid of that. That doesn't look good

**Comment by neonmoe** [comment]
I was under the impression that HTTP has a rigid concept of "lines" which always end in CR LF. After checking the rfc, it seems that it doesn't always apply to the body. Thanks for the report, a fix is on the way.

**Comment by neonmoe** [comment]
Fixed in f34cfb1ef6337ef17b080b64d3c073b7d66decf6.
