### ISSUE TITLE
Panic when downloading image

### ISSUE THREAD

**Issue by lialsoftlab** [neonmoe/minreq#13]
let url = "https://github.githubassets.com/images/modules/site/logos/ibm-logo.png"
if let Ok(response) = minreq::get(url).send() { } 

thread '<unnamed>' panicked at 'byte index 1703 is not a char boundary; it is inside 'ç' (bytes 1702..1704) of `HTTP/1.1 200 OK

  12: <alloc::string::String as core::ops::index::Index<core::ops::range::RangeFrom<usize>>>::index
             at \src\liballoc/string.rs:1971
  13: minreq::connection::read_from_stream
             at \minreq-1.2.1\src/connection.rs:191

**Comment by neonmoe** [comment]
Thanks for the report, I'll look into it.

**Comment by lialsoftlab** [comment]
I think it is consequence of using String for body... It's work's for text/* but it definitily may be not utf-8 compatible when it's image/* or application/octet-stream data. BTW you can look at https://github.com/mattgathu/minreq fork it's working in such case.

Anyway thanks for your work! :)

**Comment by iamcharleschege** [comment]
Yeah! This is a problem for images like PNGs and JPEGs. However, it works for SVGs. Is there a way to get other image formats?

**Comment by lialsoftlab** [comment]
SVG is text format (XML) and utf-8 compatible

**Comment by iamcharleschege** [comment]
I was just pointing out which images work

**Comment by neonmoe** [comment]
Yep, I'll be refactoring the whole thing to handle responses as bytes instead of strings. The API compatibility will be a bit of a problem though, since the body should really be Option<String> now. Technically I think that's a breaking change, so the major version number should be bumped, which is a bummer.

**Comment by iamcharleschege** [comment]
Could a String that doesn't enforce UTF-8 work, something like `bstr::BString` from crate `https://docs.rs/bstr/0.1.4/bstr/`

**Comment by neonmoe** [comment]
For now, I made it so that `Response::body` is just an empty string, if it isn't a valid utf8 string. In any case, `body_bytes` will contain the raw bytes.

Fixed in aa0ebe3df92cfb5c06f6c3575fe9d6bef582c02f.
