### ISSUE TITLE
Server IPv4 or Ipv6 addr

### ISSUE THREAD

**Issue by charleschege** [neonmoe/minreq#14]
Add  support for IP addresses like 127.0.0.1

**Comment by neonmoe** [comment]
I'm not sure what you mean. This already works:
```rust
fn main() {
    println!("{}", minreq::get("http://127.0.0.1").send().unwrap().body);
    // Prints out "hello", which is what I'm serving on port 80 when running this program.
}
```

**Comment by charleschege** [comment]
It only works on port 80 but not any other port especially if you add a port number after address like `http://127.0.0.1:80`.

In short, it only works with IPv4/6 addresses that have no specified port, however `localhost:[port] ` works .

Also, if a port is not open, it does not terminate the connection and return an error or timeout

**Comment by neonmoe** [comment]
Can't reproduce. I tried running the following:
```rust
fn main() {
    println!(
        "{}",
        minreq::get("http://127.0.0.1:1234").send().unwrap().body
    );
}
```
And the program printed out the correct message when the server was running on the port, and paniced at the unwrap() when there was none (ie. the connection was terminated):
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }', src/libcore/result.rs:997:5
```
Is your Rust up-to-date?

**Comment by charleschege** [comment]
I was using an older version of minreq. :pensive:

**Comment by charleschege** [comment]
@neonmoe However, the syntax in the docs is not what I am seeing here. Did the syntax change

**Comment by charleschege** [comment]
Now I am getting `ConnectionRefused` when using `127.0.0.1:8000` but I get a valid response when I use `localhost:8000`

**Comment by neonmoe** [comment]
I'm afraid you're going to need to specify your server a bit more to get help on that front, I tested my previous examples against Python's http.server, and didn't see that kind of behavior.

**Comment by charleschege** [comment]
You are right! The server I was using has a bug in dev mode, but it works fine when I move to production environment and settings
