### ISSUE TITLE
Https test fails with TLS alert 'UnexpectedMessage'

### ISSUE THREAD

**Issue by spearman** [neonmoe/minreq#2]
Here's the log output:

https://gist.github.com/spearman/28a10c35845a49deb0145929c959ab9d

Trying another url (https://canihazip.com/s) gives 'BadRecordMac' error instead of UnexpectedMessage.

**Comment by neonmoe** [comment]
I can't reproduce this, but I would guess it has something to do with your SSL certificates (since that seems to usually be the problem when it comes to ssl). But I don't really know what to fix, so I'm tagging this with "help wanted."

**Comment by spearman** [comment]
I'm going to close this here. It seems to happen for any using rustls. And I'm guessing its because it was running Ubuntu 14.04 TLS which has old packages. Tested on a newer distro and didn't have any problems.
