### ISSUE TITLE
Timeout does not work as advertised, allows DoS attacks

### ISSUE THREAD

**Issue by Shnatsel** [neonmoe/minreq#22]
`with_timeout()` is currently advertised as setting a timeout for the completion of the entire request. However, that's not what it actually does: internally the implementation [translates it to read/write timeouts](https://github.com/neonmoe/minreq/blob/267cf39bb6564aa2607c9e6f63b6f76ea6eb1d4f/src/connection.rs#L189), which only applies to a single read. This means that an established connection will keep going indefinitely if the remote host keeps replying.

This allows denial-of-service attacks; see [here](https://github.com/sbstp/attohttpc/issues/35#issuecomment-572239063) for more details.

**Comment by neonmoe** [comment]
Thanks for pointing this out, I'll look into fixing this tomorrow.

**Comment by neonmoe** [comment]
I believe the above commit fixes this.

The code review is really appreciated, thank you!
