### ISSUE TITLE
Support async 

### ISSUE THREAD

**Issue by charleschege** [neonmoe/minreq#26]
Add support for async rust

**Comment by neonmoe** [comment]
This is outside of the scope I have set for this library, sorry. That said, it might fit in as a feature, if Rust's async support allows for it without needing to change the current functionality of the crate. I'll look into this when I have the time.

**Comment by neonmoe** [comment]
Alright, I've considered this now, and come to a conclusion. I won't add async support to this crate, as that would involve (as far as I know) pulling in a big dependency that would allow for async IO. In addition to the big dependency, it would involve lots of #cfg in the internals of the crate, which would be a pain to maintain.

I recommend looking into other HTTP clients that were made with the intention to support async to begin with, such as [`reqwest`](https://crates.io/crates/reqwest).
