### ISSUE TITLE
Requests hang sometimes

### ISSUE THREAD

**Issue by Mubelotix** [neonmoe/minreq#29]
I was using minreq and I faced a strange bug making my program hang. I figured out it was coming from minreq. After debugging I found the origin of the bug.

response.rs, line 35
```rust
for byte in &mut parent {
    let (byte, length) = byte?;
    body.reserve(length);
    body.push(byte);
}
```

That loop never ends sometimes. I will try to fix that

**Comment by neonmoe** [comment]
At a glance, that seems like the server is not responding. That for loop basically just pushes each incoming byte into a vec, the hanging part will be in one of the `read_*` functions. Have you tried doing the request with a timeout?

**Comment by Mubelotix** [comment]
The server is responding (curl handle it well). But it's an empty response. I think a timeout would solve it but it should be working without. 
You are right! The last instruction of the read implementation of httpstream is hanging at connection.rs line 67

**Comment by neonmoe** [comment]
If curl can handle it, I imagine the server responds with something that should signal minreq to stop listening after a point, but it doesn't, and proceeds to get stuck waiting for a byte that never arrives. Could you link the server? That might help in identifying what this signal is, it might just be that minreq isn't handling some special header or something, which I missed in the spec.

**Comment by Mubelotix** [comment]
I found it! It's an HTTP 204 response and that means that there is no body at all! Do you want me to send a pull request? Only one condition has to be added.

**Comment by neonmoe** [comment]
Sure thing!
