### ISSUE TITLE
Do we need to keep empty response header?

### ISSUE THREAD

**Issue by KarthikNedunchezhiyan** [neonmoe/minreq#39]
In current implementation, if the response header contains ":\r\n" then it will produce ("", ""). Do we need to keep this?

context: https://github.com/neonmoe/minreq/blob/242e50b76045852094eb53e34bfca9d8451a49a6/src/response.rs#L475

**Comment by neonmoe** [comment]
I'm not sure empty headers are allowed by the spec. In any case, I can't think of a reason this would cause real-world problems, so I'm inclined to say this doesn't need fixing.

**Comment by KarthikNedunchezhiyan** [comment]
makes sense. before closing this i would like to check the rfc7231 standard supports this. will get back here soon!

**Comment by KarthikNedunchezhiyan** [comment]
I was not able to find the reason to block empty headers. so, closing this 👍
