### ISSUE TITLE
Debug logging left enabled in crates.io release

### ISSUE THREAD

**Issue by Shnatsel** [neonmoe/minreq#45]
https://github.com/neonmoe/minreq/blob/cdfd2a4f96f33a76941dc7a3efc0944fd7eb9df3/src/request.rs#L286 and below contain `println!()` statements that appear to be debug logging. It probably shouldn't be enabled by default in releases published on crates.io

**Comment by neonmoe** [comment]
Good find, didn't even notice those. I'll write a patch soon.

**Comment by neonmoe** [comment]
Searched for other cases of println too, only request.rs had printlns. Others were in tests, examples and comments.

Fixed in 84465b5ebf707121cb2ebbb9a01b309bfcb6f045.
