### ISSUE TITLE
customer provided timeout not respected during tcp connect phase

### ISSUE THREAD

**Issue by KarthikNedunchezhiyan** [neonmoe/minreq#46]
## Issue

Request may take a long time than a configured timeout or even hang because TCP connect phase has no timeout. https://github.com/neonmoe/minreq/blob/cdfd2a4f96f33a76941dc7a3efc0944fd7eb9df3/src/connection.rs#L236

## Steps to reproduce

```
minreq::Request::new(Method::Get, "http://54.158.248.248:91").with_timeout(1000).send();
```
Above code will hang for a long time even though we have configured timeout for 1sec.

@neonmoe Happy to work on resolving this once you confirm that this is actually an issue.

**Comment by neonmoe** [comment]
So it seems, as there is a [TcpStream::connect_timeout](https://doc.rust-lang.org/std/net/struct.TcpStream.html#method.connect_timeout) to cover that case. If you want to work on this, feel free!
