### ISSUE TITLE
Request timeout not honored (program hang?)

### ISSUE THREAD

**Issue by Shnatsel** [neonmoe/minreq#52]
minreq sometimes fails to uphold the request timeout and exceeds it by at least 50%. 

In my test this happened on 28033 websites out of the top million from [Feb 3 Tranco list](https://tranco-list.eu/list/3G6L).

Tested using [this code](https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/f206362f2e81521bbefb84007cdd25242f6db590/minreq-smoke-test/src/main.rs), and an external timeout on the entire process set to 60 seconds. 

Test tool output from all affected websites: [minreq-timeouts.tar.gz](https://github.com/neonmoe/minreq/files/5992249/minreq-timeouts.tar.gz)

A similar issue has been observed with other clients (e.g. ureq and attohttpc) due to them resetting the timeout on every redirection, but there it was happening on 15 websites or so, not 28,000. So I suspect something deeper is at play.

**Comment by neonmoe** [comment]
I suspect the issue lies in the timeouts "getting out of date" over the course of a request. This is a problem I remember thinking about fixing by making the entire timeout system be "timeout at instant"-based instead of "timeout after a duration", but apparently I never got around to it.

Or, since it appears in others as well, maybe there's an issue in TcpStream's timeouts. Hmm.

**Comment by neonmoe** [comment]
Address resolution seems to lack a timeout-setting function, and might take a while sometimes. Another spot where minreq seems to hang sometimes, is writing the request over https, even though the write timeout is set properly right before.

To ensure that the timeout is respected, I wrapped the entire send() function in its own thread, so now a timeout error is returned if the thread doesn't finish in time ([commit](https://github.com/neonmoe/minreq/commit/026af5aeecd44d7a9db6b9b327c8d1cf1568a762)). Not very clean, but at least it works very reliably.
