### ISSUE TITLE
Denial of service when the server sends an infinitely large header

### ISSUE THREAD

**Issue by Shnatsel** [neonmoe/minreq#55]
minreq will use an unbounded amount of memory if the server sends a single infinitely large header. This can be used to exhaust the memory on the machine and cause a denial of service.

You can reproduce the issue by running the following in Linux console and then connecting to `localhost:8080` with minreq:

`( echo -e "HTTP/1.1 200 OK\r"; echo -n "Huge-header: "; yes A | tr -d '\n' ) | nc -l localhost 8080`

Tested using [this code](https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/a5c72b32b957e621ad41800eab5cb7604d3e3282/minreq-smoke-test/src/main.rs) for minreq. You can inspect the Cargo.lock to know the exact dependency versions.

**Comment by Shnatsel** [comment]
This also works when sending a great many smaller headers.

**Comment by neonmoe** [comment]
Wrong issue tracker, or typo in crate name?

**Comment by Shnatsel** [comment]
Typo. Occurs in both, though; let me fix it. Sorry!

**Comment by Shnatsel** [comment]
Fixed now. This is what happens when I test 9 clients for 3 DoS issues each at the end of a long day.

**Comment by neonmoe** [comment]
I appreciate the effort you put into these! It's a shame I don't have the time to fix them at the same pace :smile:

**Comment by neonmoe** [comment]
Fixed in efbaf757515cd77070de5cb3e0a9ece49e20df92, though it's opt-in until 3.0.0.
