### ISSUE TITLE
Question: Would the integration of operating system specific certificates be within scope? (rusttls)

### ISSUE THREAD

**Issue by joeried** [neonmoe/minreq#58]
I recently had a project where it became necessary to accept locally installed certificates as well.

Since in my project the https-rustls feature was already used (and worked in a complex CI pipeline), I tried to extend the https-rustls feature to a https-rustls-probe feature by using https://github.com/ctz/rustls-native-certs.

This implementation seems to work. My changes can be viewed here https://gitlab.com/joedr/minreq/-/commit/6506e4582e61fe51ba80c9ffb5a4224aa39a660c
My question now would be if a pull request for such a feature would be welcomed. My changes are very small, but I would probably still need some feedback since I haven't done much with rust yet.

**Comment by neonmoe** [comment]
Such a feature would be welcome! The changes look good too, only things missing are a mention in lib.rs and the readme, to advertise the existence of the feature. I'm surprised at how small of a change it is.

A tiny nitpick: line 27 of connection.rs doesn't have a semicolon at the end of the line. I guess it technically isn't needed, but I think it'd be clearer if there was a semicolon.

**Comment by AlexAndHisScripts** [comment]
I would appreciate this too. In the meantime, is there a way to disable certificate validation?

**Comment by neonmoe** [comment]
Not within minreq, no. But I'll release a new version today or tomorrow, which has this fixed. ([PR](https://github.com/neonmoe/minreq/pull/59))

**Comment by neonmoe** [comment]
Minreq 2.4.0 has the https-rustls-probe feature for this, available now on crates.io :) Thanks again to @joeried for the PR, closing this now.
