### ISSUE TITLE
DoS via crafted content-length header

### ISSUE THREAD

**Issue by Shnatsel** [neonmoe/minreq#63]
minreq will attempt to allocate a very large amount of memory and OOM if given a content-length header with a very large value. Tested on minreq 2.4.2.

Steps to reproduce:
1. Run this script on a Linux host: [`content_length_megalomania.sh`](https://github.com/Shnatsel/http-denial-of-potatoes/blob/main/content_length_megalomania.sh)
2. Connect to localhost:8080 with minreq
3. Observe the crash

The exact code and Cargo.lock used in my tests can be found [here](https://github.com/Shnatsel/rust-http-clients-smoke-test/tree/content-length-tests/minreq-smoke-test).

cc @jhwgh1968 - your script found a bug!

**Comment by jhwgh1968** [comment]
A tip for the fix: I recommend a buffer size of 16KiB (16.384 bytes).

That is the maximum length of a TLS record, and should be fairly efficient for memory allocation and I/O on most major OSes.

**Comment by neonmoe** [comment]
Agreed, that is a good approach to this. I'll write a fix for this at some point, but I don't think this is a particularly urgent issue.
