### ISSUE TITLE
Client returns wrong status codes for missing reason phase

### ISSUE THREAD

**Issue by richarddd** [neonmoe/minreq#64]
This is currently broken behaviour. Some servers and frameworks do not return status reason phase. So a 200 without the "OK" will result in 503 which is not the case.

See https://github.com/spring-projects/spring-boot/issues/6548

Futhermore RFC7230 specifies that this reason phase should be ignored:
https://datatracker.ietf.org/doc/html/rfc7230#section-3.1.2

`A client SHOULD  ignore the reason-phrase content.`

**Comment by neonmoe** [comment]
Good to know! I do wonder where I got the idea that the status phrase shouldn't be empty. Thanks for spotting it and sending in a fix!
