### ISSUE TITLE
Failing HTTPS requests to GitHub API

### ISSUE THREAD

**Issue by tech-ticks** [neonmoe/minreq#66]
Requests to the GitHub API consistently fail with `IoError(Custom { kind: ConnectionAborted, error: "CloseNotify alert received" })` under rustls. `reqwest` returns a response with code 403 instead.

**How to reproduce:**
- Enable the `https` feature 
- `minreq::get("https://api.github.com/zen").send().unwrap();` (note that the request works if the `User-Agent` header is set)

**Comment by neonmoe** [comment]
Thanks for the report, what an odd issue. I'll look into it.

**Comment by neonmoe** [comment]
Seems to be caused by rustls 0.19, updating to 0.20 fixed it. I'll publish a patch soon.

**Comment by neonmoe** [comment]
Fixed in 841cf11b3579d4fe546d4a669182a685280219ae, released with [2.5.1](https://github.com/neonmoe/minreq/releases/tag/2.5.1).
