### ISSUE TITLE
Problems with some apis

### ISSUE THREAD

**Issue by iamcharleschege** [neonmoe/minreq#7]
Minreq is so simple and easy and I like the direction its going. However, I think it has some issues with some APIs. For example, when trying to connect to vultr.com api at https://api.vultr.com/ to get a list of all operating systems via https://api.vultr.com/v1/os/list endpoint, bearing in mind that this endpoint does not need an api key, I get a ` 503 Server did not provide a status line ` response with no headers or body. 

Also, if there is a successful response from this server even with API keys accepted where required, the responses are correct with headers but the json body is empty.

With this API, all other API tools like cURL, Rested and Postman give a successful response with the correct JSON body. I dont understand the problem, could the issue be that vultr api is upgrading to http2 from http1 and that minreq is not supporting it?

**Comment by neonmoe** [comment]
Sorry for the wait. 
It's very probably because of the http2 upgrade. I'm not sure how the status line parsing could fail, as the http2 one seems similar enough. I'm not familiar with http2 at all though, so I'll look into this further at some point.

**Comment by neonmoe** [comment]
Update on this issue: it seems that http 2 is quite different from 1.1, and since I'm currently not very much into writing another parser for a new protocol, I probably won't be touching this issue in a while. PRs are of course welcome, and I'll probably even notice them now that I've "watched" this repo.

**Comment by iamcharleschege** [comment]
I think I have found the issue, minreq does not handle _chunked encoding_ header well. Using a buf reader, the first chunk is hexadecimal 8e4 followed by the actual json data. It seems like minreq terminates after the first chunk thereby discarding other chunks including ones that contain data

**Comment by neonmoe** [comment]
Minreq certainly doesn't recognize that header, and handling it seems very doable. Thanks for debugging this, much appreciated. I'll endeavor to write a patch soon.

**Comment by iamcharleschege** [comment]
Thanks for taking care of this as fast as possible. It now works out the box :tada:

**Comment by iamcharleschege** [comment]
Sorry for taking you down the http/2 rabbit hole

**Comment by neonmoe** [comment]
No problem, at least the problem was fixed :smile:
