### ISSUE TITLE
`parse_url` returns garbage if protocol isn't provided in URL

### ISSUE THREAD

**Issue by alpha-tango-kilo** [neonmoe/minreq#70]
Noticed this while writing tests for URL encoding, if you don't specify http(s):// at the start of a URL it returns garbage data. Would probably be an idea to account for, be it by handling as implicit http, or error

Repro: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ee95eb5a4ccb2d2a75865ed9be694a26

**Comment by neonmoe** [comment]
A missing protocol should definitely return an error, similar to HttpsFeatureNotEnabled when trying to connect to `https://...` without a https feature. Kind of surprised that this isn't handled currently, honestly :sweat_smile:

**Comment by alpha-tango-kilo** [comment]
I can look at drafting a PR if you would like, or else given that it'll require some structural changes, you may wish to do so yourself - I don't mind

**Comment by neonmoe** [comment]
I'd rather do it myself, given that this will probably require a few iterations to get feeling right. Less back-and-forth in a PR and all that :)
