### ISSUE TITLE
Error when iterating non static headers

### ISSUE THREAD

**Issue by charleschege** [neonmoe/minreq#71]
If a user defines a Vec of headers like

```
#[derive(Debug)]
pub struct HTTPClient {
    url: &'static str,
    body: JsonValue,
    headers: Vec<(String, String)>,
}
```

and they are trying to iterate on `HTTPClient.headers` and adding those headers using `.with_headers()` method results in an error, for example
```
let post_tx = minreq::post(self.url);
       // Iterate over the added headers in the vec
        self.headers.iter().for_each(|header| {
            post_tx.clone().with_header(&header.0, &header.1);
        });

post_tx.send()?
```

I think the issue is brought about by line https://github.com/neonmoe/minreq/blob/878e7cbe4fe07ccb0d16ba120d2b6be113906484/src/request.rs#L140

Is there a way to get around this or can we use `fn with_header(&mut self, ...)` instead of `fn with_header(mut self, ...)` to ensure the iterator borrows instead of taking ownership

**Comment by neonmoe** [comment]
Could you do what you want with a for-loop, like this? (Note: I didn't try to compile the code, just trying to get the idea across.)
```rust
let mut post_tx = minreq::post(self.url);
for header in &self.headers {
    post_tx = post_tx.with_header(&header.0, &header.1);
}
post_tx.send()?
```

**Comment by charleschege** [comment]
already tried a for loop, still doesn't work since the loop owns the data

**Comment by neonmoe** [comment]
Here's a playground example, where I made a little module imitating minreq's API: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e1548757eca6a2932797770d0de80e9c Tested it with actual minreq too, locally. 

The headers given as parameters don't need to live past the for-loop, as `with_header()` actually makes its own clones of it. Maybe try just borrowing your headers in the for-loop (i.e. `for _ in &self.headers`)? That's what .iter() does.

**Comment by charleschege** [comment]
Thanks. Borrowing self for the for loop works
