### ISSUE TITLE
Is it possible to use minreq to send a POST request with form data?  If so, how?

### ISSUE THREAD

**Issue by wpd** [neonmoe/minreq#72]
Would it look something like this?
```
minreq::post(format!("http://127.0.0.1:8000{}", page))
            .with_body(b"x=1".to_vec())
            .send()
            .unwrap();
```
When I use this, somewhere along the line `"x=1"` gets transformed to `x&#x3D;1`.  It might be on the receiving side though.  I just don't know (yet).

**Comment by neonmoe** [comment]
Your code does indeed work as you'd expect. I set up a "server" with `nc -l 8000` and ran your code, and it got:
```
POST / HTTP/1.1
Host: 127.0.0.1:8000
Content-Length: 3

x=1
```
If you want to send form data as a POST request, manually constructing the body is the way to go. You could also send a GET request with query parameters set with `Request::with_param`, which would work similarly to a html form with the formaction set to get.

**Comment by wpd** [comment]
Hello @neonmoe, thank you.  It seems like the parameters were getting transformed by my server application.  I tried using:
```
minreq::post(format!("http://127.0.0.1:8000{}", page))
                .with_header("Content-Type", "application/x-www-form-urlencoded")
                .with_body(body)
                .send()
                .unwrap();
```
and that seemed to help.

Thank you for your help, and for your work on this crate.

--wpd
