### ISSUE TITLE
设置Host头错误

### ISSUE THREAD

**Issue by YDHCUI** [neonmoe/minreq#73]
![image](https://user-images.githubusercontent.com/46884495/162601283-932424c8-812c-41d9-84d8-434953f9a576.png)

如图示，使用with_header设置Host头时会造成出现两个Host‘头

**Comment by neonmoe** [comment]
Sending requests to one address with the Host being another doesn't seem like a regular use case to me. I understand that there are situations where you might want that, but I would rather make it very obvious that you don't need to set the Host header manually, than enable this edge-case. I'd look into other http client libraries if you need this functionality.
