### ISSUE TITLE
remove JSON

### ISSUE THREAD

**Issue by 89z** [neonmoe/minreq#77]
I like this crate because it is small, however I do not like that it has JSON:

https://github.com/neonmoe/minreq/commit/217de913e47c66f5eb5b48f2cade22a5462a66ad

Serde is one of the larger JSON packages, so it seems strange to include it with a minimal HTTP package. I think it would be better to omit it, and allow users to pick their own JSON package

**Comment by neonmoe** [comment]
It's completely optional, just don't enable the `json-using-serde` feature. It's not a default feature.
