### ISSUE TITLE
ResponseLazy std::io::Read

### ISSUE THREAD

**Issue by 89z** [neonmoe/minreq#78]
It would be nice if ResponseLazy implemented Read, that way you could use copy or similar:

https://doc.rust-lang.org/std/io/fn.copy.html

**Comment by 89z** [comment]
Looks like Cursor might do as a workaround:

https://doc.rust-lang.org/std/io/struct.Cursor.html

**Comment by neonmoe** [comment]
Good suggestion, seems useful and relatively straightforward to implement! I don't have time right now to add it though, but definitely in the future.

**Comment by 89z** [comment]
If it helps, I found an implementation here:

https://docs.rs/zeptohttpc/0.5.0/zeptohttpc/struct.BodyReader.html
