### ISSUE TITLE
要怎么 发送和读取 HTTP的协议版本 

### ISSUE THREAD

**Issue by YDHCUI** [neonmoe/minreq#82]
要怎么 发送和读取 HTTP的协议版本  正常应该是HTTP/1.1 
但是有些服务器只支持 HTTP/1.0 或 HTTP/0.9

**Comment by neonmoe** [comment]
It is not mentioned in the README, but this library is for HTTP/1.1. There is no intention to support 1.0 or 0.9, sorry.
