### ISSUE TITLE
No field 'status_code' on type 'Result<Response, minreq::Error>'

### ISSUE THREAD

**Issue by carlosm27** [neonmoe/minreq#84]
Hi everyone. I hope all of you are well.

I was trying this package for the first time, and I trying to run this code:

```
fn main() {
     let response = minreq::get("http://httpbin.org/ip").send();


     println!("{:?}",response.status_code);   
    
}

```
And every time I run it I get this error "no field `status_code` on type `Result<Response, minreq::Error>`"

The version of rustc I using is 1.64.0.

Great package by the way.

Have a nice day.

**Comment by neonmoe** [comment]
You need to extract the actual Response from the Result. Here's two examples:

If you want to just crash if the request fails:
```rust
fn main() {
    let response = minreq::get("http://httpbin.org/ip").send().unwrap();

    println!("{:?}", response.status_code);
}
```

Another way is to use a match statement:
```rust
fn main() {
    match minreq::get("http://httpbin.org/ip").send() {
        Ok(response) => println!("{:?}", response.status_code),
        Err(err) => {
            // Oh no! The request failed in this branch, do something else, maybe with `err`.
        }
    }
}
```

I'd recommend having a look at the [Rust book](https://doc.rust-lang.org/book/), specifically [Chapter 6](https://doc.rust-lang.org/book/ch06-00-enums.html) for this kind of stuff, I think you'll find that Result is a very common construct in Rust.

Have a nice day!

**Comment by carlosm27** [comment]
Thank you very much for the help and the reference.
