### ISSUE TITLE
"This app is not available on your PC" when compiling for release

### ISSUE THREAD

**Issue by bennett-sh** [neonmoe/minreq#87]
Hello, my issue is that when I add the minreq crate as a dependecy to my program (with the "https" feature) everything works fine as long as I compile it targeting dev. If I however try to compile it targeting release or using ```cargo publish```, the resulting binary will only show a "This app is not available on your PC"-message or do nothing forever when run from the terminal.

The error message:
![image](https://user-images.githubusercontent.com/110846042/213882816-0581acc6-eaae-471f-982c-7679717f8540.png)

**Comment by neonmoe** [comment]
What an odd issue. What happens when:
1. You remove the `minreq` dependency entirely, and compile in --release?
2. Include just `minreq` without any features, and compile in --release?

**Comment by bennett-sh** [comment]
So I've now found out that just including the dependency works fine. However, if I include the code I use to make the request, the message reappears.
This is the code causing the error:
````rs
pub fn get_latest_release() -> Option<serde_json::Value> {
    let request_url = "https://api.github.com/repos/bennett-sh/wemod-pro-unlocker/releases/latest";
    let request = minreq::Request::new(minreq::Method::Get, request_url)
        .with_header("User-Agent", "wmpu-cli");

    match request.send() {
        Ok(response) => {
            let text_response = match response.as_str() {
                Ok(text) => text,
                Err(err) => {
                    println!("failed to check for updates: {}", err);
                    return None;
                }
            };
            let json_response: serde_json::Value = match serde_json::from_str(text_response) {
                Ok(json) => json,
                Err(err) => {
                    println!("failed to check for updates: {}", err);
                    return None;
                }
            };

            return Some(json_response);
        }
        Err(err) => println!("failed to check for updates: {}", err),
    }

    None
}
```

**Comment by neonmoe** [comment]
Very odd. Does it happen if you change the `https` feature to one of the other variants, like `https-native`?

**Comment by bennett-sh** [comment]
```https-native``` seems to work. Thank you for the quick help.
