### ISSUE TITLE
能否支持http代理 

### ISSUE THREAD

**Issue by YDHCUI** [neonmoe/minreq#88]

**Comment by YDHCUI** [comment]
没搞明白这个代理要怎么用，使用sock5代理好像也不行。如下代码：

`fn main() -> Result<(), minreq::Error> {
    let proxy = minreq::Proxy::new("127.0.0.1:22222").unwrap();
    println!("{:?}",proxy);
    let response = minreq::get("https://ip.sb")
        .with_body("Hello, world!")
        .with_proxy(proxy)
        .send().unwrap();
    let hello = response.as_str()?;
    println!("{}", hello);
    Ok(())
}` 

报错：`      Running target\debug\rustatt.exe
Proxy { server: "127.0.0.1", port: 22222, user: None, password: None, kind: Basic }
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BadProxy', src\main.rs:7:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\rustatt.exe` (exit code: 101)`

**Comment by neonmoe** [comment]
Some kind of proxy support was contributed in #27, but it's http connect based, not socks. Socks seems like a slightly more complicated protocol, so I don't think it's a good fit for the library.
