### ISSUE TITLE
some head requests never complete

### ISSUE THREAD

**Issue by mattgathu** [neonmoe/minreq#9]
I ran into an issue when doing a `head` requests where the response is not returned:
```rust
extern crate minreq;

fn main() {
    let url = "https://httpbin.org/status/418";
    let response = minreq::head(url)
        .send()
        .unwrap();
    let headers = response.headers;

    println!("{:#?}", headers);
}
```
When a changed the http method to `get` it worked.

I suspect that the [`read_from_stream`](https://github.com/neonmoe/minreq/blob/master/src/connection.rs#L104-L136) function never quits the loop.

One way to solve this issue it to change the response body to be a stream, that is we only read the http status and headers from tcp stream and pass the body as a stream to the caller. 
That way, if the body is empty (e.g. in head requests) we never block indefinitely.

**Comment by mattgathu** [comment]
I noticed there's a `test_head` test that passes so I'm also not quite sure if this is a server implementation issue betweeen **tiny_http** *vs* **httpbin's server**

**Comment by neonmoe** [comment]
This is actually a bug in how head responses (and 1xx, 204 and 304 status codes) are handled: the spec says the message should terminate on the *first* empty line after the headers. Should be an easy fix, I'll do it in a moment.
