### ISSUE TITLE
Syn v2 release breaking MSRV?

### ISSUE THREAD

**Issue by alpha-tango-kilo** [neonmoe/minreq#93]
See failed CI run [here](https://github.com/neonmoe/minreq/actions/runs/4455735911/jobs/7825731812?pr=69)

Looks like the recently released `syn` v2 requires Rust 2021 edition, which is unsupported on the MSRV for this crate

This could be difficult to control given `syn` is a transitive dependency. We'd probably have to start pinning dependencies

**Comment by neonmoe** [comment]
Thankfully we're only getting `syn` version 2 from serde_derive, which is only needed by dev-dependencies, so I don't mind pinning the last serde version without `syn` 2 in there. Let's hope syn 2 doesn't make an appearance in the future!

(The other syn in `cargo tree` seems to be under openssl, which isn't included in the msrv anyway, so I think we're good now.)

Fixed this (and cleaned up dev-dependencies overall) in ad41004.
