### ISSUE TITLE
add async support

### ISSUE THREAD

**Issue by moneyball** [neonmoe/minreq#97]

**Comment by neonmoe** [comment]
Sorry, I won't. See: #26

**Comment by devrandom** [comment]
FWIW, as a data point, the VLS Project (https://vls.tech/) is a security focused library that would benefit from a concise HTTP library with less dependencies, to reduce attack surface area.  However, we do use async because it is a more natural way to express multi-tasking.

**Comment by neonmoe** [comment]
I recommend writing your own, you can customize it to your specific needs, and a HTTP client isn't too big of a project. Honestly kind of an ideal thing to do yourself, if you're concerned about dependencies. That's why I made this!

**Comment by BEULAHEVANJALIN** [comment]
> Hmm, we'd also like to use it in our project, so it'd be nice to have some kind of common-ish one, supporting async is relatively easy these days, you just macro-ize the socket read and make the function optionally-async (probably just macro-ize the whole thing and duplicate it async+not - we have it implemented at https://github.com/lightningdevkit/rust-lightning/blob/main/lightning-block-sync/src/http.rs#L227 but the client itself is overly hacky there). While its true we could keep using our own HTTP client, its not _completely_ trivial - we'd like to support not only HTTP but also pluggable support for TLS, make sure the implementation is robust, etc, which takes a nontrivial amount of work, and part of why we were excited about using minreq :).

I've implemented async version of minreq https://github.com/BEULAHEVANJALIN/async-minreq
